### ISSUE TITLE
No module named constants

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/batch4py#1]
```
Traceback (most recent call last):
  File "simple.py", line 1, in <module>
    import batch4py
  File "/u/sciteam/clipp/.local/lib/python3.5/site-packages/batch4py/__init__.py", line 1, in <module>
    import constants
ImportError: No module named 'constants'
```

**Comment by LandonTClipp** [comment]
Fixed in d138f0cc4a9efb77595817f7a96926ab37e3c0db
